### ISSUE TITLE
Things to improve for v0.5

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/name-sans-roadmap#28]
Main upgrades:

- [ ] Reduce x-height in display to allow tighter kerning between T & lowercase (WIP at https://github.com/arrowtype/name-sans-roadmap/issues/31)
- [x] Make case-specific accents (will improve line heights, as well as looking better)
  - [x] Add case dot & dieresis to 200 supports
  - [ ] fix `Gbreve Oslashacute Idotaccent`
- [x] Test simpler size-specific swap system: https://github.com/arrowtype/name-sans-roadmap/issues/35
- [x] make stylistic sets more consistent/compatible between static & variable fonts (https://github.com/arrowtype/name-sans-roadmap/issues/33)
- [x] Add northeast/northwest/southeast/southwest arrows
- [x] Add leftright & updown arrows
- [x] add specific `y` for bold vs lighter weights, with smooth connection in bold+.
  - [x] also add diacritics if you do
  - [x] add this to kerning groups with `y`
  - [x] make specific feature edit to static display bold–ultra  to activate `y.bold` and `y.ultra_calt` which needed.
  - [ ] Make y swap to `.bold` version above 650 (not 550)
- [x] Add accented versions of `R.RECTgrot` to glyphs & features
- [x] Support glyphs between 700 & 1000, where contrast gets a bit non-ideal `E S a e s w` etc
- [x] Add supports for a few critical glyphs at display 500: `S a s &`
- [x] check stem thickness / contrast in display bold `f C N S X Y & ?`
- [x] thicken inside tail of `Q` in display bold
- [x] remove `fi` ligature (set to non-exporting)
- [x] update apertures of figures in display bold
  - [ ] update apertures of figures in other styles: text, hairline, ultra, etc
- [ ] Some of the accents get too light at lighter weights – they need supports at the boldest weight where they can match stroke thickness (maybe 400 or 500)? This includes the dot for `i`, `j`, etc.
- [x] case-specific punctuation
- [ ] superiors & inferiors
- [ ] Add fractions
- [x] Make horns smooth in Text styles
- [ ] Update currencies to (recently modified) tabular figure spacing
- [ ] Add auxiliary characters for Norwegian: `Ŋ ŋ Ŧ ŧ Ǎ ǎ`
- [x] add missing `×` character (multiply)
- [x] more-specific `7`? (like 79th street) – if so, move to `tnum` UPDATE: tested, but it’s not as good. Revert.
- [ ] fix ogoneks in Text styles

Designspace
- [x] test: can you automatically add a "Heading Regular" source as the default position? This may solve some OS bugs.
- [x] test: find slightly-wider "Standard" style and replace "Heading" with this
- [x] Should auto R.grot happen above 72 pt (rather than 24)?

Kerning:
- [x] fix Display Ultra `ay` pair (currently crashes)
- [ ] Display Bold `RY`
- [ ] `R.text T`
- [ ] Make sure `T.ultra` matches `T` for all kerns except lowercase
- [ ] add `t.ultra` to `t` right group, or kern separately

Little fixes:
- [x] flatten top & bottom of parentheses
- [x] make arrowtails & arrowheads (significantly) larger in Text styles
- [x] improve leg shape of `&` at regularish weights
- [x] Cut crossbar of A to avoid macOS render bug
- [ ] Check kerning on `A W.rect`, `O.rect S`
- [ ] improve sizing of dot at Text Regular sizes
- [ ] improve contrast of $ bar in medium-ish weights
- [x] improve contrast of Oslash.RECT bar in medium-ish weights
- [x] fix weight of Ohorn, ohorn, etc at Text Ultra, check elsewhere
- [ ] add/fix Eth.RECT, Oslashacute.open, Oslashacute_open.RECT
- [x] make prime & double-prime correct/simplified shape
- [ ] check kern in wght 200 `lys`
- [ ] check angle on terminals of `S` around wght 200
- [x] Make `k` slightly wider at display bold
- [x] Make `R.text` slightly wider, to better match `R` curly
- [x] `C` should be _slightly_ narrower at display bold, to optically match O

Technical fixes:
- [x] the "friendly name" is incorrect (it’s “v0.3” where it should be “v0.4”), though the formal & build versions are correct
- [x] `rvrn` is currently not predictable ... "open" letters (like $ or Q) go open at their minimum, but then waver – fixed by including `optical size` in `conditionset`s

To explore:
- [ ] Precise angles of terminals in extended characters: currencies, section, etc

- [x] (?) Increase top size to 144 for hairline style? If so, recalculate opsz mapping

**Comment by arrowtype** [comment]
Adjust spacing in branch `main-v05-spacing` slightly. To do:

- [ ] start text ultra
- [ ] update diacritics to match
- [ ] update support sources
