### ISSUE TITLE
Version 0.8

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/name-sans-roadmap#48]
**Fixes/refinements to v0.7**
- [x] fix stylistic set 14
  - [x] change `&` to `and` in statics
  - [x] fix missing oldstyle + high legibility 9
- [x] fix dots in `¿!;:` around 200–500 weight range (inconsistent sizing and height)
- [x] fix placement of ¿ in Text Italic middle weight range
- [x] Update trial font to have all accents but limited symbols
- [x] check and add unicodes to superscripts (and subscripts?)
- [x] check whether `won` needs a Unicode fix or addition – ￦ vs ₩
- [x] (probably) make subscripts sit below the baseline
- [x] Fix titling diereses in Display & Text Italic
- [x] Fix ordinals that are missing or need feature code additions (#29)
  - [x] `Mgr` (Mgr – Monseigneur) (probably just needs extra fea code)
  - [x] `Mlle` (Mlle – Madmoiselle) (probably just needs extra fea code)
  - [x] `re` and `RE` (1re – première)
  - [x] `D` and `d` (2d – second, masculine version))
  - [x] `ième`, `IÈME` for Nième ([nth in French](https://en.wikipedia.org/wiki/Superior_letter#Use_in_French))
    - [x] `e`, `E`, Me for maître (['Maestro' in French](https://en.wikipedia.org/wiki/Superior_letter#Use_in_French)) and XXe siècle ('twentieth century'), etc
    - [x] `o`, `O`, Mo for métro ('subway').
    - [x] [there are more possible french abbreviations...](https://en.wikipedia.org/wiki/Superior_letter#Use_in_French) ... but at some point, this would really just need a full alphabet of superiors, which doesn’t seem quite necessary to claim much-better-than-average ordinal indicator support.
  - [x] `as`, `os`, `AS`, `OS` for [plural ordinals in Spanish](https://en.wikipedia.org/wiki/Superior_letter#Use_in_Spanish)
  - [ ] also look into `S LL ÉE G`, originally noted in this todo item
  - [x] add new ordn additions to main fea code, then copy this into other static fea code files (look at build again to determine why there are multiples...)
- [ ] fix `A T.ultra` kern in italics (also check uprights)
- [x] add support source for `&` at 100 to keep it a little more monolinear
- [x] check that `nine.tnum_hiviz` contrast matches `six.tnum_hiviz` at weight 200, and that it builds, because nine.hiviz at weight 200 has just been decomposed
- [x] Prefix naming with `AT`
- [x] make script to check (and maybe update) spacing in sparse sources, by interpolated glyphs from main sources.
- [x] check and make corrections with list at https://github.com/arrowtype/name-sans-roadmap/issues/49
- [ ] slightly raise joint of y.simple
- [x] widen endash (and .case version) in all styles (keep within same tnum width)
- [x] make underscore wider (research/experiment to decide by how much)
- [x] make bracket and slash punctuation taller
  - [x] `[ ] ( ) { }`
  - [x] `| ¦ / \`
  - [x] make slashes slightly less angled
    - [x] and .case versions
  - [x] give `|` more L/R margins
    - [x] copy to case bar, 
  - [x] copy changes to italics, then duplicate margins with `copy-specified-sidebearings-all_uprights_to_italics.py`
  - [x] rekern for new shapes
    - [x] group slash.case with slash, backslash.case w/ backslash, and check results
    - [x] split out groups for case parens vs brackets+braces
- [x] make display ultra /Omega nicer
  - [x] copy over to display ultra italic

**New problems**
- [x] figure out why the `“` (left double quote) has odd spacing in VF italic. Maybe you just need to decompose it...
- [x] fix flipping interpolation in `¿` (along opsz axis in italics)

**Extensions**
- [x] rearrange stylistic sets for better grouping, e.g. G/g early, a options adjacent
- [x] make `a.default`, etc, to allow stylistic sets to work
  - [x] add to kerning groups
  - [ ] make "a.simple" glyphs to allow both sets to work in VFs
  - [x] make new fea code for static italics? Or can "a.simple" make things work?
- [x] Add a "boring" `g`
  - [x] also add diacritics
- [x] Add a "boring" `G`
  - [x] also add diacritics
- [x] Add brutalist asterisk: with 6 points and little to no contrast
- [ ] streamline build using makefile, etc 
- [ ] Display Italics
  - [x] adjust support drawings for lower contrast
    - [ ] reduce contrast at text 200 italic
  - [ ] maybe: make drawings slightly narrower to better pair with uprights
  - [x] fix `ocircumflextilde ohorntilde` in display ultra italic
  - [x] take a second pass as round letters
  - [x] Check /quotedblleft compatibility
  - [x] figure out the best way to make a.italic happen by default, but be possible to toggle off
  - [ ] fix display ultra /a.italic
  - [x] eliminate rightwards shift that happens at support locations: https://github.com/arrowtype/name-sans-roadmap/issues/50
- [x] ~Make flat-bottomed /at symbol?~ Tested, but it looks too complex
- [x] ? Add Rupee
- [ ] Add `Q.titl`?
- [ ] Add top/bottom anchors to all base glyphs, for better `mark` feature
- [ ] Add top/bottom anchors to all accent glyphs, for better `mkmk` feature
- [ ] add actual sinf, sups glyphs
  - [x] move sinf down by a few tile grid units
  - [ ] add to kerning (probably just group with numr, then kern sinf)
  - [x] add to features
  - [ ] proof
- [x] add missing acaron.italic to all fonts

**Italics**
- [ ] fix `L_periodcentered_L.loclCAT`, etc
- [x] check & fix spacing in slash, backslash (and case versions)
- [x] copy new Display Ultra faux italics into unfixed / non-present Display Ultra Italics
  - [ ] fix shaping in 6/9 hiviz
  - [ ] determine which glyphs are missing from italics (especially Display Ultra Italics)
- [ ] copy (?) spacing from uprights to italics
- [ ] fix kerning, especially in diagonals
- [x] decompose dots in titling diereses glyphs, fix alignment etc

**Drawing adjustments**
- [x] make Q tail small in display bold
- [x] Italics: try thickening the top joint of italic letters like `a d g`, to reduce the big whitespace in those joints
  - [x] text bold
  - [x] text ultra
  - [x] text hairline
- [x] thin out dots in display hairline to match other strokes
- [ ] unify overshoots in .RECT glyphs?
- [ ] (?) italics: adjust terminals of `two three question`, decide whether to update
- [x] (?) Should some symbols be taller by default? `number slash bracket` etc
- [ ] add support glyphs for `Germandbls thorn`
- [ ] `r` right margin should match or be smaller than `t` left margin... it might currently be slightly bigger? (Look at `ryt` as a test), in Display Regular
- [x] ~Maybe the thin/hairline `1` should be a right-angle form, and the rvrn could be a lot more subtle. The right angle version just looks way cooler than the "grotesque" hairline version.~ Nah, it just isn't as legible.
- [x] make hairline /Germandbls wider
- [x] should hairline quotes have more internal space? probably...
- [x] text bold: make contrast of /r more similar to /n

**Kerning**
- [ ] check "mvp diagonals" in all sources (esp. Vc, Wc, Yc, vo, wo, yo, etc)
- [ ] check kerning in former o group glyphs (e, b, d, etc, g, c), esp. Text
- [x] check `//` for URLs
- [ ] check asterisk in Italic DB, Italic DH (there are no kerns there, despite kerns in other sources)
- [x] Kern numbers to Uppercase
- [x] ? kern numbers to lowercase?
- [x] split /three side1 out of /eight side1 group
- [ ] adjust kerning in Italics
  - [ ] diagonals, basics
  - [ ] quotes, dashes
  - [ ] full ABCs?
- [ ] Text `o` is kerned a little too tight against diagonals at Regular & Reg Italic
- [ ] Kern numerals to letters, esp. in display
- [ ] fix L side1 – L is currently an exception, so Ł (Lslash) doesn’t get those kerns
- [ ] decide if glyph order is okay, or fix
- [ ] Split Oslash.open and Oslash.RECT into new groups, kern
- [ ] Re-check T and T.ultra
- [ ] Copy exceptions from `T` to lower over to `Tcedilla`, `Tcommaaccent`, and `Tcaron`
- [ ] proof and improve case punctuation kerns
- [ ] improve proofing, especially for quote marks & T pairs
- [x] kern space and J
- [x] re-kern `¿Y` (especially in display italic)

**Features**
- [x] Consider adjusting opsz axis: Text could go smaller
  - [x] adjust RVRN if so
  - [x] Readjust "Standard" location
  - [ ] Make Display Hairline a little thicker, then let the ultra-thin hairline be used at even larger sizes?
- [x] Finish STAT table
- [x] Add stylistic set to GSUB to have a stylistic set for double-story `a` (`ss15`, to not interfere with current alts) (started in branch `ss15`, but may need rewrite of GSUB?) 
- [ ] determine how to make "regular" instance work in MS Word, on Windows 11 (currently defaults to hairline)

**Naming/Metadata**
- [x] Should family or style names be adjusted? https://github.com/arrowtype/name-sans-roadmap/issues/15

**Techy Explorations**
- [ ] Build PDF specimen generator w/ drawbot
- [ ] Create a makefile-based build? ([example](https://github.com/aliftype/amiri/blob/main/Makefile))

**Maybe, maybe not**
- [x] Boring `g` stylistic set? (non-flat descender) (bonus: would probably work in `g` kerning groups...)
- [x] Round `G` stylistic set? (bonus: would probably work in `O` kerning groups...)
- [ ] optional raised colon for clock times? (but with what OT feature?)

**Comment by arrowtype** [comment]
Proof the following, and fix kerning where necessary:

```
aTa àTà áTá âTâ ãTã äTä åTå āTā ăTă ąTą ạTạ ảTả ấTấ ầTầ ẩTẩ ẫTẫ ậTậ ắTắ ằTằ ẳTẳ ẵTẵ ặTặ bTb cTc çTç ćTć čTč dTd ďTď eTe èTè éTé êTê ëTë ēTē ĕTĕ ėTė ęTę ěTě ẹTẹ ẻTẻ ẽTẽ ếTế ềTề ểTể ễTễ ệTệ fTf gTg ğTğ ģTģ hTh iTi ìTì íTí îTî ïTï ĩTĩ īTī ĭTĭ įTį ỉTỉ ịTị jTj kTk ķTķ lTl ĺTĺ ļTļ ľTľ mTm nTn ñTñ ńTń ņTņ ňTň oTo òTò óTó ôTô õTõ öTö ōTō ŏTŏ őTő ơTơ ọTọ ỏTỏ ốTố ồTồ ổTổ ỗTỗ ộTộ ớTớ ờTờ ởTở ỡTỡ ợTợ pTp qTq rTr ŕTŕ ŗTŗ řTř sTs śTś şTş šTš tTt ťTť uTu ùTù úTú ûTû üTü ũTũ ūTū ŭTŭ ůTů űTű ųTų ưTư ǔTǔ ụTụ ủTủ ứTứ ừTừ ửTử ữTữ ựTự vTv wTw xTx yTy ýTý ÿTÿ ỳTỳ ỵTỵ ỷTỷ ỹTỹ zTz źTź żTż žTž ßTß æTæ ðTð øTø ǿTǿ þTþ đTđ ıTı ĳTĳ łTł œTœ ȷTȷ μTμ πTπ aVa àVà áVá âVâ ãVã äVä åVå āVā ăVă ąVą ạVạ ảVả ấVấ ầVầ ẩVẩ ẫVẫ ậVậ ắVắ ằVằ ẳVẳ ẵVẵ ặVặ bVb cVc çVç ćVć čVč dVd ďVď eVe èVè éVé êVê ëVë ēVē ĕVĕ ėVė ęVę ěVě ẹVẹ ẻVẻ ẽVẽ ếVế ềVề ểVể ễVễ ệVệ fVf gVg ğVğ ģVģ hVh iVi ìVì íVí îVî ïVï ĩVĩ īVī ĭVĭ įVį ỉVỉ ịVị jVj kVk ķVķ lVl ĺVĺ ļVļ ľVľ mVm nVn ñVñ ńVń ņVņ ňVň oVo òVò óVó ôVô õVõ öVö ōVō ŏVŏ őVő ơVơ ọVọ ỏVỏ ốVố ồVồ ổVổ ỗVỗ ộVộ ớVớ ờVờ ởVở ỡVỡ ợVợ pVp qVq rVr ŕVŕ ŗVŗ řVř sVs śVś şVş šVš tVt ťVť uVu ùVù úVú ûVû üVü ũVũ ūVū ŭVŭ ůVů űVű ųVų ưVư ǔVǔ ụVụ ủVủ ứVứ ừVừ ửVử ữVữ ựVự vVv wVw xVx yVy ýVý ÿVÿ ỳVỳ ỵVỵ ỷVỷ ỹVỹ zVz źVź żVż žVž ßVß æVæ ðVð øVø ǿVǿ þVþ đVđ ıVı ĳVĳ łVł œVœ ȷVȷ μVμ πVπ aFa àFà áFá âFâ ãFã äFä åFå āFā ăFă ąFą ạFạ ảFả ấFấ ầFầ ẩFẩ ẫFẫ ậFậ ắFắ ằFằ ẳFẳ ẵFẵ ặFặ bFb cFc çFç ćFć čFč dFd ďFď eFe èFè éFé êFê ëFë ēFē ĕFĕ ėFė ęFę ěFě ẹFẹ ẻFẻ ẽFẽ ếFế ềFề ểFể ễFễ ệFệ fFf gFg ğFğ ģFģ hFh iFi ìFì íFí îFî ïFï ĩFĩ īFī ĭFĭ įFį ỉFỉ ịFị jFj kFk ķFķ lFl ĺFĺ ļFļ ľFľ mFm nFn ñFñ ńFń ņFņ ňFň oFo òFò óFó ôFô õFõ öFö ōFō ŏFŏ őFő ơFơ ọFọ ỏFỏ ốFố ồFồ ổFổ ỗFỗ ộFộ ớFớ ờFờ ởFở ỡFỡ ợFợ pFp qFq rFr ŕFŕ ŗFŗ řFř sFs śFś şFş šFš tFt ťFť uFu ùFù úFú ûFû üFü ũFũ ūFū ŭFŭ ůFů űFű ųFų ưFư ǔFǔ ụFụ ủFủ ứFứ ừFừ ửFử ữFữ ựFự vFv wFw xFx yFy ýFý ÿFÿ ỳFỳ ỵFỵ ỷFỷ ỹFỹ zFz źFź żFż žFž ßFß æFæ ðFð øFø ǿFǿ þFþ đFđ ıFı ĳFĳ łFł œFœ ȷFȷ μFμ πFπ
```

**Comment by arrowtype** [comment]
Things to clean up in sources (required to generate fonts with makeOTF... which is required for Font Proofer):
- remove R.text, Rcedilla.text
- remove uni2010 (it’s a duplicate of /hyphenproper)
- export kerning to features

**Comment by arrowtype** [comment]
Flat-bottomed /at symbol. Idea inspired by Verdana. Seems to better match the spirit of Name!

<img width="667" alt="image" src="https://user-images.githubusercontent.com/45946693/212392983-4b9c439d-1f86-4518-95b3-7b4a14b6772d.png">

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/45946693/212393011-defd63f3-d827-4504-a65e-11944d49b20c.png">

**Comment by arrowtype** [comment]
A discussion of superiors/inferiors, relevant to figures added in this round: 
https://typedrawers.com/discussion/860/superior-superscript-inferior-subscript-and-ordinals

**Comment by arrowtype** [comment]
Won sign:
> The [Unicode](https://en.wikipedia.org/wiki/Unicode) code point is U+20A9 ₩ WON SIGN: this is valid for either appearance. Additionally, there is a full width character at U+FFE6 ￦ FULLWIDTH WON SIGN (in the block [halfwidth and fullwidth forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)). — [source](https://en.wikipedia.org/wiki/Won_sign)

**Comment by arrowtype** [comment]
Useful testing string:

HH/? HH\nOO/? OO\nnn/? nn\noo/? oo\nHH//H\H|H/brokenbar HH\nHH(H){H}[H]HH

**Comment by arrowtype** [comment]
HH//H\H|H/brokenbar HH\n HH/slash.case H/backslash.case H/bar.case H/brokenbar.case HH \nHH(H){H}H[H]H⟨H⟩HH\nHH/parenleft.case H/parenright.case H/braceleft.case H/braceright.case /bracketleft.case H/bracketright.case H/anglebracketleft.case H/anglebracketright.case HH

**Comment by arrowtype** [comment]
Notes on kerning slashes...

Not many fonts are particularly careful about kerning slashes to lowercase...

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/45946693/219479741-3c0ccf84-a946-43a9-9c3a-e808870104e9.png">

I’ve kerned them fairly painstakingly for the Display sources, but I will try going a lot faster in the Text sources:
- transform slashes to 0 for uppercase
- make "MVP" slash kerning pair list: a-z, V, W, Y, J, 1, 4, 7

Also look into transforming braces (maybe scale kerns by 200% for text sources?)

**Comment by arrowtype** [comment]
Scaling braces & brackets in Text:
- [x] text hairline (threshold and shift of 50, then corrected lowercase)
- [ ] text bold
- [ ] text ultra

Next
- [ ] Copy new kerning over to italics

**Comment by arrowtype** [comment]
Look at next:

- [ ] NS Italic VF has `Regular` for nameID 2. Should it be `Italic`, or does that not matter in a VF?

```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      AT Name Sans Variable
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
```

**Comment by arrowtype** [comment]
- [ ] create new ordering for stylistic sets:

1. Rectangular Uppercase
2. Grotesque Uppercase "R"
3. Serif Uppercase "I"
4. Simplified Lowercase "l"
5. Simplified Uppercase "G"
6. Simplified Lowercase "g"
7. Double-story Lowercase "g"
8. Single-story Lowercase "a"
9. Double-story "a" in Italics
10. Simplified Lowercase "t"
11. Simplified Lowercase "y"
12. Simplified Lowercase "j"
13. High-legibility 6 & 9
14. Brutalist Punctuation
15. Blackletter Eszett
16. Ligated IJ
17. Titling Uppercase Umlauts
18. [blank]
19. Grotesque "R" in Display
20.  High-legibility "I, l, g" in Text

**Comment by arrowtype** [comment]
- [x] fix `.default` alt diacritic glyphs at support locations... see below

Display Regular, `a` and its diacritics:

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/45946693/220367204-8e643602-e65f-4d1d-8d41-284c9d53056d.png">

Display Regular, `a.default` and its diacritics (used in a stylistic set for the italics):

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/45946693/220367352-1c6218c7-eea8-4230-ac8c-a62d9ed3158c.png">

This could probably be corrected by either: 
- pointing those alt diacritics to `a`, rather than `a.default`, or
- adding `a.default` to the support sources (yup! this did it)
... but it would take some testing to know for sure.

**Comment by arrowtype** [comment]
Closing due to release of v0.8. 

Open to-do items transfered to #53
